%YAML:1.0
imu_topic: "/imu/data"
image_topic: "/camera/image_raw"
output_path: "/root/vins_output/"
model_type: PINHOLE
camera_name: camera
image_width: 640
image_height: 480
distortion_parameters:
   k1: 0.0
   k2: 0.0
   p1: 0.0
   p2: 0.0
projection_parameters:
   fx: 381.361150
   fy: 381.361150
   cx: 320.0
   cy: 240.0
estimate_extrinsic: 1
extrinsicRotation: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [0, -1, 0,
          0, 0, -1,
          1, 0, 0]
extrinsicTranslation: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   data: [0.3, 0.0, 0.3]
max_cnt: 150
min_dist: 30
freq: 10
F_threshold: 1.0
show_track: 1
equalize: 1
fisheye: 0
max_solver_time: 0.04
max_num_iterations: 8
keyframe_parallax: 10.0
acc_n: 0.08
gyr_n: 0.004
acc_w: 0.00004
gyr_w: 2.0e-6
g_norm: 9.81007
loop_closure: 0
load_previous_pose_graph: 0
fast_relocalization: 0
pose_graph_save_path: "/root/vins_output/pose_graph/"
estimate_td: 0
td: 0.0
rolling_shutter: 0
rolling_shutter_tr: 0
save_image: 0
visualize_imu_forward: 0
visualize_camera_size: 0.4
